In [257]:
import random
import numpy as np
import pandas as pd

In [258]:
test = np.array([
    #     a1
    [
        1, -1, -1, 1, -1, -1, -1,
        -1, -1, -1, 1, -1, -1, -1,
        -1, -1, 1, -1, 1, -1, -1,
        -1, -1, 1, -1, 1, -1, -1,
        -1, -1, 1, 1, 1, -1, 1,
        -1, 1, -1, -1, -1, 1, -1,
        -1, 1, -1, 1, -1, 1, -1,
        1, -1, -1, 1, -1, -1, 1,
        1, -1, -1, 1, -1, -1, 1,
    ],

    #     a2
    [
        1, -1, -1, 1, -1, -1, 1,
        -1, -1, -1, 1, -1, 1, -1,
        1, -1, 1, -1, 1, -1, 1,
        -1, -1, 1, -1, 1, -1, 1,
        1, -1, 1, 1, 1, -1, 1,
        -1, 1, 1, -1, -1, 1, -1,
        -1, 1, -1, 1, -1, 1, 1,
        1, -1, 1, 1, -1, -1, 1,
        1, -1, -1, 1, -1, 1, 1,
    ],
    #     a13
    [
        -1, -1, -1, 1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 1, -1, -1,
        -1, -1, -1, -1, 1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, 1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, 1,
        -1, -1, -1, -1, -1, -1, 1,
    ],
    #     a4
    [
        1, -1, -1, 1, -1, -1, 1,
        -1, -1, -1, 1, -1, -1, -1,
        1, -1, 1, -1, 1, -1, -1,
        -1, -1, 1, -1, 1, -1, -1,
        1, -1, 1, 1, 1, -1, 1,
        -1, 1, -1, -1, -1, 1, -1,
        -1, 1, -1, 1, -1, 1, 1,
        1, -1, -1, 1, -1, -1, 1,
        1, -1, -1, 1, -1, -1, 1,
    ],
    #     a5
    [
        -1, -1, -1, 1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, -1, 1, -1, 1, -1, -1,
        -1, -1, -1, -1, 1, -1, -1,
        -1, -1, 1, -1, 1, -1, -1,
        -1, 1, -1, -1, -1, -1, -1,
        -1, 1, -1, -1, -1, -1, -1,
        1, -1, -1, -1, -1, -1, 1,
        1, -1, -1, -1, -1, -1, 1,
    ],
    #     a6
    [
        -1, -1, -1, 1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, 1,
    ],
    #     a7
    [
        1, -1, -1, 1, -1, -1, 1,
        -1, -1, -1, 1, -1, 1, -1,
        1, -1, 1, -1, 1, -1, -1,
        -1, -1, 1, -1, 1, -1, -1,
        1, -1, 1, 1, 1, -1, 1,
        -1, 1, 1, -1, -1, 1, -1,
        -1, 1, -1, 1, -1, 1, 1,
        1, -1, -1, 1, -1, -1, 1,
        1, -1, -1, 1, -1, -1, 1,
    ],
    #     a8
    [
        -1, -1, -1, 1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 1, -1, -1,
        -1, -1, -1, -1, 1, -1, -1,
        -1, -1, 1, -1, -1, -1, -1,
        -1, 1, -1, -1, -1, -1, -1,
        -1, 1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, 1,
        -1, -1, -1, -1, -1, -1, 1,
    ],
    #     a9
    [
        -1, -1, 1, 1, -1, 1, -1,
        -1, 1, -1, 1, 1, -1, -1,
        1, -1, 1, 1, 1, -1, 1,
        -1, -1, -1, -1, 1, 1, -1,
        -1, 1, 1, 1, -1, -1, -1,
        1, 1, -1, 1, -1, 1, 1,
        -1, 1, 1, -1, -1, -1, -1,
        1, 1, -1, -1, 1, -1, 1,
        -1, -1, -1, 1, -1, -1, -1,
    ],
    #     b1
    [
        -1, 1, 1, -1, 1, -1, -1,
        1, -1, 1, -1, -1, -1, -1,
        1, 1, -1, -1, 1, -1, 1,
        -1, -1, -1, 1, -1, -1, -1,
        1, 1, -1, 1, 1, 1, -1,
        1, 1, -1, -1, 1, -1, -1,
        -1, -1, -1, 1, -1, -1, -1,
        1, -1, 1, -1, -1, -1, -1,
        1, -1, 1, 1, -1, -1, -1,
    ],
    #     c
    [
        1, -1, 1, -1, 1, -1, 1,
        -1, 1, 1, -1, -1, -1, -1,
        1, 1, -1, -1, 1, -1, 1,
        -1, -1, -1, 1, -1, -1, 1,
        1, -1, 1, -1, -1, 1, -1,
        1, 1, -1, -1, 1, -1, -1,
        -1, -1, -1, 1, -1, -1, -1,
        -1, 1, 1, -1, -1, -1, -1,
        -1, 1, 1, 1, -1, -1, -1,
    ],

])

In [259]:
data = pd.read_csv('data/data.csv')
output = pd.read_csv('data/labeldata.csv')
output.head(10)

label  pixel 0  pixel 1  pixel 2  pixel 3  pixel 4  pixel 5  pixel 6  \
0      1       -1        1       -1        1       -1        1        1   
1      2        1        1       -1        1       -1        1        1   
2      3        1        1        1        1       -1       -1        1   

   pixel 7  pixel 8  pixel 9  pixel 10  pixel 11  pixel 12  pixel 13  pixel 14  
0        1        1        1        -1         1         1        -1         1  
1        1       -1        1        -1         1         1         1        -1  
2       -1       -1        1        -1        -1         1         1         1

In [260]:
input_size = 63
output_size = 15

activation_fn = lambda x: np.where(x > 0, 1, -1)


def hebbian_learning(inputs, outputs):
    weights = np.zeros((input_size, output_size))
    for x, y in zip(inputs, outputs):
        #print(x, y)
        weights += np.outer(x, y)
    #print(weights)
    return weights

In [261]:
def test_hebbian_network(test_data, weights):
    raw_output = np.dot(test_data, weights)
    #print(raw_output)
    hebb_output = activation_fn(raw_output)
    return hebb_output

In [262]:
d_train_X = np.array(data.drop(['label'], axis=1))
d_train_y = np.array(output.drop(['label'], axis=1))

In [263]:
#print(d_train_X)
#print(d_train_y)

In [264]:
hebbian_weights = hebbian_learning(d_train_X, d_train_y)
#print(hebbian_weights)

In [265]:
def find_most_similar(test_vector, candidate_vectors):
    similarities = np.dot(candidate_vectors, test_vector)
    most_similar_index = np.argmax(similarities)
    return most_similar_index

In [266]:
for test_data in test:
    output = test_hebbian_network(test_data, hebbian_weights)
    print(output)
    if np.array_equal(output, d_train_y[0]):
        print("A")
    elif np.array_equal(output, d_train_y[1]):
        print("B")
    elif np.array_equal(output, d_train_y[2]):
        print("C")
    else:
        print("?")
        most = find_most_similar(output, d_train_y)
        match most:
            case 0:
                print("A")
            case 1:
                print("B")
            case 2:
                print("C")
               

[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
A
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
A
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
A
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
A
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
A
[ 1  1 -1  1 -1  1  1  1 -1  1 -1  1  1  1  1]
?
B
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
A
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
A
[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
A
[ 1  1 -1  1 -1  1  1  1 -1  1 -1  1  1  1 -1]
B
[ 1  1  1  1 -1 -1  1 -1 -1  1 -1 -1  1  1  1]
C
